[logger]
    mode = "debug"
    timestamp = "time"

[authorization]
    [[authorization.users]]
        username = "username"
        password = "password"

[api]
    enable = true
    auth = true
    env = "development"

[web]
    enable = true
    auth = false

[input]
    enable = true
    auth = false
    env = "development"
    [input.parsing]
        enable = true
    [input.receivers]
        [input.receivers.telegraf_json]
            enable = true